#!/bin/bash
# Caffeine toggle - prevents screen from locking/dimming

if pgrep -x "hypridle" > /dev/null; then
    killall hypridle
    notify-send "Caffeine ON" "Screen will not lock" -i display-brightness-symbolic
else
    hypridle &
    notify-send "Caffeine OFF" "Idle timer restored" -i display-brightness-symbolic
fi
