#!/usr/bin/env bash
# archScratch - deploy dotfiles (symlinks with backup)

source "$(dirname "$0")/global_fn.sh"

BACKUP_DIR="$HOME/.config-backup-$(date +%Y%m%d-%H%M%S)"

backup_file() {
    # Move a real file/dir (or foreign symlink) into the timestamped backup dir.
    local target="$1"
    mkdir -p "$BACKUP_DIR"
    mv "$target" "$BACKUP_DIR/"
    print_warn "Backed up $target → $BACKUP_DIR/"
}

backup_and_link() {
    local src="$1"   # source file/dir in repo
    local dest="$2"  # destination path

    # Never create a dangling symlink to a missing source.
    if [[ ! -e "$src" ]]; then
        print_err "Source missing, skipping: $src"
        return 1
    fi

    if [[ -L "$dest" ]]; then
        # If the existing symlink already points into this repo, just refresh it;
        # otherwise it's the user's own link — preserve it by backing it up.
        local cur
        cur="$(readlink -f "$dest" 2>/dev/null)"
        if [[ "$cur" == "$DOTFILES_DIR"/* ]]; then
            rm -f "$dest"
        else
            backup_file "$dest"
        fi
    elif [[ -e "$dest" ]]; then
        backup_file "$dest"
    fi

    mkdir -p "$(dirname "$dest")"
    ln -sf "$src" "$dest"
    print_ok "Linked $dest"
}

deploy_configs() {
    print_header "Deploying ~/.config dotfiles"
    local cfg="$DOTFILES_DIR/Configs"
    local d
    for d in hypr waybar foot kitty wofi mako nvim fastfetch gtk-3.0 gtk-4.0 \
             Kvantum qt5ct qt6ct waypaper zathura; do
        backup_and_link "$cfg/$d" "$HOME/.config/$d"
    done
}

deploy_machine_conf() {
    # ~/.config/hypr is a symlink into the repo, so write the machine-specific
    # config there; it's gitignored and regenerated on every deploy.
    print_header "Generating machine-specific Hyprland config"
    local out="$DOTFILES_DIR/Configs/hypr/machine.conf"

    # Detect an NVIDIA GPU by PCI vendor (0x10de) — works before drivers load.
    local has_nvidia=false
    if grep -qli '^0x10de' /sys/bus/pci/devices/*/vendor 2>/dev/null \
       || lspci 2>/dev/null | grep -qi nvidia; then
        has_nvidia=true
    fi

    {
        echo "# Generated by restore_cfg.sh — regenerated on every deploy, do not edit."
        if [[ "$has_nvidia" == "true" ]]; then
            cat <<'EOF'
# NVIDIA GPU detected (https://wiki.hypr.land/Nvidia/)
env = NVD_BACKEND,direct
cursor {
    no_hardware_cursors = true
}
# Uncomment if the desktop renders on the dGPU (mux/dGPU-only mode):
# env = LIBVA_DRIVER_NAME,nvidia
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia
EOF
        else
            echo "# No NVIDIA GPU detected — nothing machine-specific needed."
        fi
    } > "$out"
    print_ok "machine.conf generated (NVIDIA: $has_nvidia)"
}

deploy_local_bin() {
    print_header "Deploying ~/.local/bin scripts"
    mkdir -p "$HOME/.local/bin"
    shopt -s nullglob
    local script name
    for script in "$DOTFILES_DIR/local-bin/"*; do
        name="$(basename "$script")"
        chmod +x "$script"   # no-op when already +x in the repo (keeps git clean)
        backup_and_link "$script" "$HOME/.local/bin/$name"
    done
    shopt -u nullglob
}

deploy_home_files() {
    print_header "Deploying home dotfiles"
    backup_and_link "$DOTFILES_DIR/home/.zshrc" "$HOME/.zshrc"
}

deploy_wallpapers() {
    print_header "Setting up wallpapers"
    mkdir -p "$HOME/Pictures/Wallpapers"
    shopt -s nullglob
    local wp name count=0
    for wp in "$DOTFILES_DIR/Wallpapers/"*; do
        name="$(basename "$wp")"
        if [[ ! -e "$HOME/Pictures/Wallpapers/$name" ]]; then
            cp "$wp" "$HOME/Pictures/Wallpapers/$name" && count=$((count + 1))
        fi
    done
    shopt -u nullglob
    print_ok "Wallpapers ready in ~/Pictures/Wallpapers/ ($count new)"
}

deploy_systemd_user() {
    print_header "Deploying systemd user units"
    local src="$DOTFILES_DIR/Configs/systemd/user"
    [[ -d "$src" ]] || { print_warn "No systemd user units to deploy"; return 0; }
    mkdir -p "$HOME/.config/systemd/user"
    shopt -s nullglob
    local unit name
    for unit in "$src"/*; do
        name="$(basename "$unit")"
        backup_and_link "$unit" "$HOME/.config/systemd/user/$name"
    done
    shopt -u nullglob
    systemctl --user daemon-reload 2>/dev/null || true
    if systemctl --user enable --now wallpaper-rotate.timer 2>/dev/null; then
        print_ok "wallpaper-rotate.timer enabled"
    else
        print_warn "Could not enable wallpaper-rotate.timer now (it will start on next login)"
    fi
}

deploy_greetd() {
    print_header "Configuring greetd"
    local cfg="$DOTFILES_DIR/system/greetd-config.toml"
    local dest="/etc/greetd/config.toml"
    sudo mkdir -p /etc/greetd
    if [[ -e "$dest" ]]; then
        sudo cp "$dest" "${dest}.archscratch-bak.$(date +%Y%m%d-%H%M%S)" \
            && print_warn "Backed up existing $dest"
    fi
    # Use | as the sed delimiter so a username never collides with the pattern.
    sed "s|{{USER}}|$USER|g" "$cfg" | sudo tee "$dest" > /dev/null
    print_ok "greetd configured for user: $USER"
}

main() {
    deploy_configs
    deploy_machine_conf
    deploy_local_bin
    deploy_home_files
    deploy_wallpapers
    deploy_systemd_user
    deploy_greetd
    print_ok "All dotfiles deployed"
    [[ -d "$BACKUP_DIR" ]] && print_warn "Backups saved to: $BACKUP_DIR"
}

main "$@"
